package com.taxiscan.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.widget.*;
import org.json.JSONArray;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class MainActivity extends Activity {
  static final int BG=Color.rgb(9,13,12), CARD=Color.rgb(24,29,27), LINE=Color.rgb(53,61,57), YELLOW=Color.rgb(255,214,0), GREEN=Color.rgb(51,211,133), MUTED=Color.rgb(155,170,162), WHITE=Color.rgb(241,246,243), RED=Color.rgb(244,112,103);
  static final String PREF="taxiscan_v2";
  SharedPreferences prefs; LinearLayout root, content; String current="Головна";
  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);prefs=getSharedPreferences(PREF,MODE_PRIVATE);if(!prefs.contains("trial_start"))prefs.edit().putLong("trial_start",System.currentTimeMillis()).apply();showHome();}
  int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  TextView text(String s,int color,int size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextColor(color);v.setTextSize(size);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
  GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
  LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
  LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
  void setup(String title, boolean back){root=col();root.setBackgroundColor(BG);LinearLayout bar=row();bar.setPadding(dp(20),dp(13),dp(18),dp(13));if(back){TextView b=text("‹",WHITE,31,false);b.setOnClickListener(v->showHome());bar.addView(b);TextView t=text(title,WHITE,19,true);t.setPadding(dp(12),0,0,0);bar.addView(t);}else{TextView a=text("Taxi",YELLOW,25,true),b=text("Scan",GREEN,25,true);bar.addView(a);bar.addView(b);View spacer=new View(this);bar.addView(spacer,new LinearLayout.LayoutParams(0,1,1));TextView pro=text("★",YELLOW,23,true);pro.setOnClickListener(v->showPremium());bar.addView(pro);}root.addView(bar);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);content=col();content.setPadding(dp(18),dp(8),dp(18),dp(18));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
  void showHome(){current="Головна";setup("TaxiScan",false);content.addView(title("Помічник водія таксі","Радар • чистий дохід • фільтри"));
    LinearLayout hero=card();LinearLayout r=row();LinearLayout l=col();l.addView(pill(accessibilityEnabled()?"РАДАР АКТИВНИЙ":"РАДАР ВИМКНЕНО",accessibilityEnabled()?GREEN:YELLOW));TextView h=text(accessibilityEnabled()?"Стеження за замовленнями":"Увімкніть радар замовлень",WHITE,20,true);h.setPadding(0,dp(10),0,dp(5));l.addView(h);l.addView(text("Bolt • Uklon • Uber",MUTED,13,false));r.addView(l,new LinearLayout.LayoutParams(0,-2,1));TextView radar=text("◉",GREEN,60,true);r.addView(radar);hero.addView(r);hero.addView(button(accessibilityEnabled()?"Перевірити радар":"Налаштувати дозволи",GREEN,()->showPermissions()));content.addView(hero);
    LinearLayout metrics=row();metrics.addView(metric("Сьогодні",fmt(todayGross())+" ₴",YELLOW),new LinearLayout.LayoutParams(0,-2,1));metrics.addView(metric("Поїздки",String.valueOf(todayCount()),WHITE),new LinearLayout.LayoutParams(0,-2,1));metrics.addView(metric("За годину",fmt(todayHourly())+" ₴",GREEN),new LinearLayout.LayoutParams(0,-2,1));content.addView(metrics);
    section("Остання пропозиція");JSONObject last=lastEvent();content.addView(last==null?empty("Очікуємо замовлення","Коли розпізнаємо пропозицію у вибраному сервісі, тут з’явиться її оцінка."):offerCard(last));
    section("Калькулятор замовлення");LinearLayout calc=card();EditText fare=field("Сума замовлення, ₴","",true),distance=field("Маршрут, км","",true),pickup=field("Подача до пасажира, км","0",true);calc.addView(fare);calc.addView(distance);calc.addView(pickup);TextView verdict=text("Вкажіть суму та кілометраж",MUTED,14,true);verdict.setPadding(0,dp(8),0,dp(10));calc.addView(verdict);calc.addView(button("Порахувати чистий дохід",GREEN,()->{double f=num(fare),d=num(distance),p=num(pickup),fuel=prefs.getFloat("cost_km",2.5f),commission=prefs.getFloat("commission",15f);double net=f*(1-commission/100)-(d+p)*fuel;double perKm=d+p>0?net/(d+p):0;boolean good=perKm>=prefs.getFloat("min_km",10)&&f>=prefs.getFloat("min_fare",80)&&p<=prefs.getFloat("max_pickup",3);verdict.setText((good?"✓ ВИГІДНО":"× НЕВИГІДНО")+"\nЧистий дохід: "+fmt(net)+" ₴  •  "+fmt(perKm)+" ₴/км");verdict.setTextColor(good?GREEN:RED);}));content.addView(calc);
    section("Швидкий доступ");grid(new String[][]{{"⚙","Фільтри","filters"},{"▱","Дозволи","permissions"},{"☷","Журнал і статистика","stats"},{"★","Premium","premium"}});
    bottomNav();}
  void bottomNav(){LinearLayout nav=row();nav.setPadding(dp(4),dp(9),dp(4),dp(9));nav.setBackgroundColor(Color.rgb(16,20,18));String[][] a={{"⌂","Головна"},{"◉","Радар"},{"▤","Статистика"},{"⚙","Налаштування"}};for(String[] item:a){LinearLayout tab=col();tab.setGravity(Gravity.CENTER);int color=item[1].equals(current)?GREEN:MUTED;tab.addView(text(item[0],color,19,true));tab.addView(text(item[1],color,10,false));tab.setOnClickListener(v->{if(item[1].equals("Радар"))showPermissions();else if(item[1].equals("Статистика"))showStats();else if(item[1].equals("Налаштування"))showDriver();else showHome();});nav.addView(tab,new LinearLayout.LayoutParams(0,-2,1));}root.addView(nav);}
  void showFilters(){current="Фільтри";setup("Фільтри замовлень",true);section("ПАРАМЕТРИ ВИГІДНОСТІ");Switch only=toggle("Показувати лише вигідні","Решту пропозицій панель приховує",prefs.getBoolean("only_good",true));content.addView(only);addSlider("Мінімум за км",0,30,prefs.getInt("min_km",10),"₴/км","min_km");addSlider("Мінімум за годину",0,600,prefs.getInt("min_hour",250),"₴/год","min_hour");addSlider("Макс. подача до пасажира",0,10,prefs.getInt("max_pickup",3),"км","max_pickup");addSlider("Мінімальна сума",0,300,prefs.getInt("min_fare",80),"₴","min_fare");addSlider("Мін. рейтинг пасажира",30,50,prefs.getInt("min_rating",46),"","min_rating",true);section("ПРИКЛАДИ");content.addView(empty("180 ₴ • 7,2 км • подача 1,2 км — ВИГІДНО","95 ₴ • 6,8 км • подача 4,1 км — приховано за фільтром"));content.addView(button("Зберегти",GREEN,()->{prefs.edit().putBoolean("only_good",only.isChecked()).apply();toast("Фільтри збережено");showHome();}));}
  void addSlider(String name,int min,int max,int value,String unit,String key){addSlider(name,min,max,value,unit,key,false);}void addSlider(String name,int min,int max,int value,String unit,String key,boolean decimal){LinearLayout c=card();LinearLayout r=row();r.addView(text(name,WHITE,15,true),new LinearLayout.LayoutParams(0,-2,1));TextView val=text(sliderFormat(value,decimal)+" "+unit,GREEN,15,true);r.addView(val);c.addView(r);SeekBar sb=new SeekBar(this);sb.setMax(max-min);sb.setProgress(Math.max(0,Math.min(max-min,value-min)));sb.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));sb.setThumbTintList(android.content.res.ColorStateList.valueOf(GREEN));sb.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean u){val.setText(sliderFormat(p+min,decimal)+" "+unit);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){prefs.edit().putInt(key,b.getProgress()+min).apply();}});c.addView(sb);content.addView(c);}
  String sliderFormat(int v,boolean dec){return dec?String.format(Locale.US,"%d,%d",v/10,v%10):String.valueOf(v);}
  void showDriver(){current="Налаштування";setup("Налаштування водія",true);section("РОЗРАХУНОК ДОХОДУ");content.addView(configCard("Витрати авто на 1 км", "cost_km", 2.5f, "₴/км"));content.addView(configCard("Комісія сервісу", "commission", 15f, "%"));section("СТЕЖЕННЯ ЗА СЕРВІСАМИ");for(String svc:new String[]{"Uklon","Bolt","Uber Driver"}){String key=svc.startsWith("Uber")?"service_uber":"service_"+svc.toLowerCase(Locale.US).replace(" ","");Switch s=toggle(svc,"Додавати пропозиції в журнал",prefs.getBoolean(key,!svc.startsWith("Uber")));s.setOnCheckedChangeListener((b,v)->prefs.edit().putBoolean(key,v).apply());content.addView(s);}section("ЗВУК");Switch sound=toggle("Сигнал нового замовлення","Відтворити сигнал при розпізнаванні",prefs.getBoolean("sound",true));sound.setOnCheckedChangeListener((b,v)->prefs.edit().putBoolean("sound",v).apply());content.addView(sound);LinearLayout modes=row();modes.addView(button("Медіа",GREEN,()->prefs.edit().putString("sound_mode","media").apply()),new LinearLayout.LayoutParams(0,-2,1));modes.addView(button("Будильник",CARD,()->prefs.edit().putString("sound_mode","alarm").apply()),new LinearLayout.LayoutParams(0,-2,1));content.addView(modes);section("ЖУРНАЛ ПОДІЙ");JSONArray events=events();if(events.length()==0)content.addView(empty("Поки немає подій","Увімкніть доступність і відкрийте застосунок таксі."));else{LinearLayout c=card();for(int i=events.length()-1;i>=Math.max(0,events.length()-8);i--){JSONObject e=events.optJSONObject(i);if(e!=null)c.addView(text(e.optString("time")+"   "+e.optString("service")+" • "+e.optString("amount")+" ₴ • "+e.optString("distance")+" км",WHITE,13,true));}content.addView(c);}LinearLayout actions=row();actions.addView(button("Пауза",YELLOW,()->{prefs.edit().putBoolean("paused",!prefs.getBoolean("paused",false)).apply();toast(prefs.getBoolean("paused",false)?"Радар на паузі":"Радар увімкнено");}),new LinearLayout.LayoutParams(0,-2,1));actions.addView(button("Очистити",CARD,()->{prefs.edit().putString("events","[]").apply();showDriver();}),new LinearLayout.LayoutParams(0,-2,1));content.addView(actions);section("СТАТИСТИКА ЗА ВЕСЬ ЧАС");LinearLayout stats=row();stats.addView(metric("Uklon",""+countService("uklon")+" под.",YELLOW),new LinearLayout.LayoutParams(0,-2,1));stats.addView(metric("Bolt",""+countService("bolt")+" под.",GREEN),new LinearLayout.LayoutParams(0,-2,1));stats.addView(metric("Uber",""+countService("uber")+" под.",WHITE),new LinearLayout.LayoutParams(0,-2,1));content.addView(stats);bottomNav();}
  LinearLayout configCard(String title,String key,float def,String unit){LinearLayout c=card();LinearLayout r=row();r.addView(text(title,WHITE,14,true),new LinearLayout.LayoutParams(0,-2,1));r.addView(text(fmt(prefs.getFloat(key,def))+" "+unit,GREEN,14,true));c.addView(r);c.addView(button("Змінити",CARD,()->editNumber(title,key,def)));return c;}
  void editNumber(String title,String key,float def){EditText e=field(title,String.valueOf(prefs.getFloat(key,def)),true);new AlertDialog.Builder(this).setTitle(title).setView(e).setNegativeButton("Скасувати",null).setPositiveButton("Зберегти",(d,w)->{try{prefs.edit().putFloat(key,Float.parseFloat(e.getText().toString().replace(",","."))).apply();showDriver();}catch(Exception x){toast("Перевірте значення");}}).show();}
  void showPermissions(){current="Дозволи";setup("Дозволи",true);section("ГОТОВНІСТЬ РАДАРА");LinearLayout progress=card();int ready=(accessibilityEnabled()?1:0)+(Settings.canDrawOverlays(this)?1:0)+(batteryAllowed()?1:0);progress.addView(text("Готовність системи       "+ready+" з 3",GREEN,16,true));ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(3);pb.setProgress(ready);pb.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));progress.addView(pb);progress.addView(text("Увімкніть дозволи, щоб радар працював стабільно.",MUTED,13,false));content.addView(progress);
    LinearLayout c=card();permissionRow(c,"◉","Доступність","Читає пропозиції на екрані вибраних сервісів",accessibilityEnabled(),()->new AlertDialog.Builder(this).setTitle("Доступність TaxiScan").setMessage("TaxiScan зчитуватиме видимий текст у вибраних застосунках таксі, щоб локально оцінювати суму та відстань. Дані залишаються на пристрої й не надсилаються на сервер. Увімкніть службу лише якщо погоджуєтесь.").setNegativeButton("Скасувати",null).setPositiveButton("Відкрити налаштування",(d,w)->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))).show());permissionRow(c,"▣","Поверх інших застосунків","Плаваюча панель із розрахунком",Settings.canDrawOverlays(this),()->{if(Build.VERSION.SDK_INT>=23)startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));});permissionRow(c,"ϟ","Без обмежень батареї","Щоб система не вимикала стеження",batteryAllowed(),()->requestBattery());content.addView(c);LinearLayout note=card();note.addView(text("TaxiScan обробляє текст локально. Увімкніть доступність лише якщо хочете аналізувати пропозиції на екрані.",MUTED,13,false));content.addView(note);content.addView(button("Перевірити готовність",GREEN,()->{showPermissions();toast("Готовність: "+ready+" із 3");}));bottomNav();}
  void permissionRow(LinearLayout parent,String icon,String name,String desc,boolean enabled,Runnable action){LinearLayout r=row();r.setPadding(0,dp(12),0,dp(12));LinearLayout t=col();t.addView(text(icon+"   "+name,WHITE,15,true));t.addView(text(desc,MUTED,12,false));r.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView b=text(enabled?"Увімкнено":"Увімкнути",enabled?GREEN:YELLOW,13,true);b.setPadding(dp(8),dp(7),dp(8),dp(7));b.setOnClickListener(v->action.run());r.addView(b);parent.addView(r);View line=new View(this);line.setBackgroundColor(LINE);parent.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));}
  void requestBattery(){try{Intent i=new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName()));startActivity(i);}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}
  boolean batteryAllowed(){if(Build.VERSION.SDK_INT<23)return true;android.os.PowerManager p=(android.os.PowerManager)getSystemService(POWER_SERVICE);return p.isIgnoringBatteryOptimizations(getPackageName());}
  boolean accessibilityEnabled(){String id=getPackageName()+"/"+TaxiAccessibilityService.class.getName();String enabled=Settings.Secure.getString(getContentResolver(),Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES);return enabled!=null&&enabled.toLowerCase(Locale.US).contains(id.toLowerCase(Locale.US));}
  void showPremium(){current="Premium";setup("Premium",true);long elapsed=System.currentTimeMillis()-prefs.getLong("trial_start",System.currentTimeMillis());long left=Math.max(0,24*60*60*1000L-elapsed);LinearLayout c=card();c.setBackground(bg(Color.rgb(28,31,19),18));c.addView(text(left>0?"Пробний період 24 години":"Пробний період завершено",YELLOW,20,true));c.addView(text(left>0?"Залишилось "+(left/3600000)+" год "+((left/60000)%60)+" хв":"Безкоштовні 24 години минули. Оформіть підписку, щоб продовжити.",WHITE,16,true));ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(24*60);pb.setProgress((int)Math.min(24*60,elapsed/60000));pb.setProgressTintList(android.content.res.ColorStateList.valueOf(YELLOW));c.addView(pb);content.addView(c);section("ЩО ВХОДИТЬ");LinearLayout list=card();for(String feature:new String[]{"✓  Радар замовлень Bolt, Uklon, Uber","✓  Чистий дохід, ₴/км і ₴/год","✓  Вердикт «Вигідно» / «Невигідно»","✓  Фільтри за ₴/км, подачею, рейтингом","✓  Журнал і статистика по сервісах"})list.addView(text(feature,WHITE,15,true));content.addView(list);LinearLayout offer=card();offer.setBackground(bg(YELLOW,18));offer.addView(text("★   Premium • щомісяця",BG,17,true));offer.addView(text("Скасувати можна будь-коли в Google Play. Ціна має показуватись Google Play.",BG,13,false));content.addView(offer);content.addView(button("Оформити Premium",GREEN,()->toast("Підключіть продукт підписки в Google Play Console для запуску покупок.")));content.addView(button("Керувати підпискою",CARD,()->toast("Посилання керування з’явиться після підключення Google Play Billing.")));content.addView(text("Після 24 годин повний доступ потребуватиме активної підписки.",MUTED,12,false));}
  void showStats(){current="Статистика";setup("Журнал і статистика",true);section("СЬОГОДНІ");LinearLayout r=row();r.addView(metric("Розпізнано",String.valueOf(todayCount()),WHITE),new LinearLayout.LayoutParams(0,-2,1));r.addView(metric("Сума пропозицій",fmt(todayGross())+" ₴",GREEN),new LinearLayout.LayoutParams(0,-2,1));content.addView(r);section("ПО СЕРВІСАХ");for(String svc:new String[]{"Uklon","Bolt","Uber"})content.addView(metric(svc,countService(svc.toLowerCase(Locale.US))+" замовлень • "+fmt(serviceGross(svc.toLowerCase(Locale.US)))+" ₴",WHITE));section("ОСТАННІ ПОДІЇ");JSONArray a=events();if(a.length()==0)content.addView(empty("Журнал порожній","Події з’являться після дозволу на доступність."));else for(int i=a.length()-1;i>=0;i--){JSONObject e=a.optJSONObject(i);if(e!=null)content.addView(offerCard(e));}bottomNav();}
  void grid(String[][] items){for(int i=0;i<items.length;i+=2){LinearLayout r=row();for(int j=i;j<Math.min(i+2,items.length);j++){String[] a=items[j];LinearLayout c=card();c.addView(text(a[0],a[2].equals("premium")?YELLOW:GREEN,22,true));c.addView(text(a[1],WHITE,14,true));c.setOnClickListener(v->{switch(a[2]){case"filters":showFilters();break;case"permissions":showPermissions();break;case"stats":showStats();break;default:showPremium();}});r.addView(c,new LinearLayout.LayoutParams(0,-2,1));}content.addView(r);}}
  LinearLayout card(){LinearLayout c=col();c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(bg(CARD,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(10);c.setLayoutParams(p);return c;}
  LinearLayout title(String a,String b){LinearLayout c=col();c.setPadding(0,dp(8),0,dp(15));c.addView(text(a,WHITE,23,true));c.addView(text(b,MUTED,13,false));return c;}
  void section(String s){TextView t=text(s,WHITE,14,true);t.setPadding(0,dp(18),0,dp(9));content.addView(t);}
  LinearLayout metric(String a,String b,int color){LinearLayout c=card();c.addView(text(a,MUTED,11,false));TextView t=text(b,color,17,true);t.setPadding(0,dp(4),0,0);c.addView(t);return c;}
  TextView button(String s,int color,Runnable click){TextView b=text(s,BG,15,true);b.setGravity(Gravity.CENTER);b.setPadding(dp(12),dp(13),dp(12),dp(13));b.setBackground(bg(color,14));b.setOnClickListener(v->click.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(8);b.setLayoutParams(p);return b;}
  Switch toggle(String title,String subtitle,boolean checked){Switch s=new Switch(this);s.setText(title+"\n"+subtitle);s.setTextColor(WHITE);s.setTextSize(14);s.setChecked(checked);s.setPadding(dp(12),dp(8),dp(12),dp(8));s.setBackground(bg(CARD,16));s.setButtonTintList(android.content.res.ColorStateList.valueOf(GREEN));return s;}
  TextView pill(String s,int col){TextView t=text(s,col,10,true);t.setPadding(dp(8),dp(5),dp(8),dp(5));t.setBackground(bg(Color.rgb(25,46,36),20));return t;}
  LinearLayout empty(String a,String b){LinearLayout c=card();c.addView(text(a,WHITE,14,true));c.addView(text(b,MUTED,12,false));return c;}
  LinearLayout offerCard(JSONObject o){LinearLayout c=card();String svc=o.optString("service","Taxi");double fare=o.optDouble("amount"),km=o.optDouble("distance"),pickup=o.optDouble("pickup");boolean good=o.optBoolean("good");c.addView(text(svc+" • "+fmt(fare)+" ₴ • "+fmt(km)+" км",WHITE,15,true));c.addView(text((good?"✓ ВИГІДНО":"× НЕВИГІДНО")+"   •   подача "+fmt(pickup)+" км",good?GREEN:RED,13,true));c.addView(text(o.optString("time",""),MUTED,11,false));return c;}
  EditText field(String hint,String val,boolean num){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setSingleLine(true);e.setTextColor(WHITE);e.setHintTextColor(MUTED);e.setTextSize(14);e.setInputType(num?android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL:android.text.InputType.TYPE_CLASS_TEXT);e.setPadding(dp(12),dp(8),dp(12),dp(8));e.setBackground(bg(Color.rgb(34,40,37),10));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(8);e.setLayoutParams(p);return e;}
  double num(EditText e){try{return Double.parseDouble(e.getText().toString().replace(',','.'));}catch(Exception x){return 0;}}
  String fmt(double x){return String.format(new Locale("uk","UA"),"%.1f",x);}
  Switch toggle(String title,String subtitle,boolean checked,CompoundButton.OnCheckedChangeListener l){Switch s=toggle(title,subtitle,checked);s.setOnCheckedChangeListener(l);return s;}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
  JSONArray events(){try{return new JSONArray(prefs.getString("events","[]"));}catch(Exception e){return new JSONArray();}}
  JSONObject lastEvent(){JSONArray a=events();return a.length()>0?a.optJSONObject(a.length()-1):null;}
  int todayCount(){int n=0;String today=day();JSONArray a=events();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&o.optString("iso").startsWith(today))n++;}return n;}
  double todayGross(){double s=0;String d=day();JSONArray a=events();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&o.optString("iso").startsWith(d))s+=o.optDouble("amount");}return s;}
  double todayHourly(){int n=todayCount();return n==0?0:todayGross()/Math.max(1,(System.currentTimeMillis()-prefs.getLong("shift_start",System.currentTimeMillis()))/3600000.0);}
  int countService(String svc){int n=0;JSONArray a=events();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&o.optString("service").toLowerCase(Locale.US).contains(svc))n++;}return n;}
  double serviceGross(String svc){double s=0;JSONArray a=events();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&o.optString("service").toLowerCase(Locale.US).contains(svc))s+=o.optDouble("amount");}return s;}
  String day(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
}
